os: linux

language: go

git:
  depth: 1

go:
  - 1.14.x
env:
  GO111MODULE=on

notifications:
  email: false

install:
  - sudo apt-get install npm
  - sudo npm -g install webpack webpack-cli --save-dev
  - . ./.travis_ninja.sh
  - go get -u github.com/roman-mazur/bood/cmd/bood

script:
  - cd $GOPATH/src/github.com/mdapathy/arch-design-2/build
  - bood
  - rm build.bood
  - mv build.boodtdma build.bood
  - ./out/bin/boodtdma
  - cat ./out/js/my-script.js
  - cat ./out/reports/test.txt
